### ISSUE TITLE
Add bottom border to toolbar for One Light/Dark UI themes

### ISSUE THREAD

**Issue by nunocastromartins** [suda/tool-bar#157]
At some point in time, Atom's bottom bar became full width.
This caused the toolbar to look like this when using One Light/Dark UI themes:

![without-border](https://cloud.githubusercontent.com/assets/8314616/17459787/2041bed8-5c40-11e6-8020-c265f616fe9f.png)

Please look at the lack of a bottom border on the toolbar.
With a border it looks like this (much better in my opinion):

![with-border](https://cloud.githubusercontent.com/assets/8314616/17459786/20400a2a-5c40-11e6-8b8b-e5a6607ca0e1.png)

The style used to add the border (although I'm sure you don't need it, just adding it for completeness):

```less
// Styling for one-dark/light-ui theme
.theme-one-dark-ui, .theme-one-light-ui {
  // Add border bottom to vertical tool-bar
  .tool-bar.tool-bar-vertical {
    border-bottom: 1px solid @base-border-color;
  }
}
```
