### ISSUE TITLE
Show Bar on Mouse Hover

### ISSUE THREAD

**Issue by liuderchi** [suda/tool-bar#191]
It's more like a sharing rather than an issue.

Just adding following snippet in our `~/.atom/styles.less`

```less
@toolBarSizeHidden: 1px;
@barSizeWhenIcon12px: 30px;
@barSizeWhenIcon16px: 38px;
@barSizeWhenIcon24px: 54px;
@barSizeWhenIcon32px: 70px;
// NOTE barSize = 2*iconSize + 6px
@transitionTime: 1000ms;

.tool-bar-top, .tool-bar-bottom{
  height: @toolBarSizeHidden;
  transition: height @transitionTime;
  &:hover {
    height: @barSizeWhenIcon24px;
    transition: height @transitionTime;
  }
}
.tool-bar-left, .tool-bar-right {
  width: @toolBarSizeHidden;
  transition: width @transitionTime;
  &:hover {
    width: @barSizeWhenIcon24px;
    transition: width @transitionTime;
  }
}
```
You can replace with different variables according to your icon size.

Now you can show tool-bar by just moving your mouse which is easier for me.
