### ISSUE TITLE
Alternative ways to provide icons

### ISSUE THREAD

**Issue by idleberg** [suda/tool-bar#271]
In the past, breaking changes in this package's icon fonts made me upgrade my own packages which consume `tool-bar` as service. So, I was wondering if there are safer alternatives to icon fonts, that prevent my own packages from breaking.

### Data URIs

**Example:**

Use in custom toolbar

```js
toolBar.addButton({
  icon: 'wand',
  callback: 'my-package:take-photo',
  tooltip: 'Take Photo',
  dataURI: 'image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJmZWF0aGVyIGZlYXRoZXItYXBlcnR1cmUiPjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjEwIj48L2NpcmNsZT48bGluZSB4MT0iMTQuMzEiIHkxPSI4IiB4Mj0iMjAuMDUiIHkyPSIxNy45NCI+PC9saW5lPjxsaW5lIHgxPSI5LjY5IiB5MT0iOCIgeDI9IjIxLjE3IiB5Mj0iOCI+PC9saW5lPjxsaW5lIHgxPSI3LjM4IiB5MT0iMTIiIHgyPSIxMy4xMiIgeTI9IjIuMDYiPjwvbGluZT48bGluZSB4MT0iOS42OSIgeTE9IjE2IiB4Mj0iMy45NSIgeTI9IjYuMDYiPjwvbGluZT48bGluZSB4MT0iMTQuMzEiIHkxPSIxNiIgeDI9IjIuODMiIHkyPSIxNiI+PC9saW5lPjxsaW5lIHgxPSIxNi42MiIgeTE9IjEyIiB4Mj0iMTAuODgiIHkyPSIyMS45NCI+PC9saW5lPjwvc3ZnPg=='
});
```

Resulting button

```html
<button data-original-title="" title="" class="btn btn-default tool-bar-btn"
style="
  background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJmZWF0aGVyIGZlYXRoZXItYXBlcnR1cmUiPjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjEwIj48L2NpcmNsZT48bGluZSB4MT0iMTQuMzEiIHkxPSI4IiB4Mj0iMjAuMDUiIHkyPSIxNy45NCI+PC9saW5lPjxsaW5lIHgxPSI5LjY5IiB5MT0iOCIgeDI9IjIxLjE3IiB5Mj0iOCI+PC9saW5lPjxsaW5lIHgxPSI3LjM4IiB5MT0iMTIiIHgyPSIxMy4xMiIgeTI9IjIuMDYiPjwvbGluZT48bGluZSB4MT0iOS42OSIgeTE9IjE2IiB4Mj0iMy45NSIgeTI9IjYuMDYiPjwvbGluZT48bGluZSB4MT0iMTQuMzEiIHkxPSIxNiIgeDI9IjIuODMiIHkyPSIxNiI+PC9saW5lPjxsaW5lIHgxPSIxNi42MiIgeTE9IjEyIiB4Mj0iMTAuODgiIHkyPSIyMS45NCI+PC9saW5lPjwvc3ZnPg==);
  background-repeat: no-repeat;
  background-position: center;
"></button>
```

### Path to image

Similarly to the data URI approach, another option could be to provide a path to an image.

**Example:**

```js
const packagePath = atom.packages.resolvePackagePath('my-package');
const imagePath = path.resolve(packagePath, 'images', 'aperture.svg');

toolBar.addButton({
  icon: 'wand',
  callback: 'my-package:take-photo',
  tooltip: 'Take Photo',
  imagePath: imagePath
});
```

There might be other ways that I can't think of. Maybe this issue is a good starting point for a discussion. If you're in favour of either method, I'm willing to submit a PR for this feature.

**Comment by suda** [comment]
That's an interesting idea 🤔 The main goal of bundling the icons with `tool-bar` was to have a unified look and stop packages from using low-res/low-quality images for the buttons.

I think what happened with `ionicons` update was more of a testing gap. We're not testing if any of the icons got resolved, so any breaking change in the icon set can cause downstream problems. I would maybe suggest another approach:

1. Introduce tests that validate that each icon has been resolved
2. If icons get removed, maintain a "backward compatibility table" that would map the old icons with a replacement

What are your thoughts @ericcornelissen, @UziTechn @jerone?

**Comment by ericcornelissen** [comment]
@suda, something like that is definitely a good idea. Though personally I'm not opposed to the proposal by @idleberg. I get that you want to keep a unified look but I don't think it makes sense within the Atom ecosystem (Atom puts barely any restrictions on what you make your packages look like, they just make it easy to use their style). However, I think it needs a bit more thinking before implementing it.

The _data URI_ thing is interesting as it seems a bit limited in scope in my opinion, it doesn't really allow for different approaches such as using a custom icon font. Same for the _path to image_ approach...

I think a better approach would be to allow users to specify a (list of) classes for the button. Then the user should make sure there is a style sheet in place which provides the necessary styling for the button through that class. This covers the use cases described above. E.g. for the _data URI_ approach:

```js
toolBar.addButton({
  icon: 'wand',
  callback: 'my-package:take-photo',
  tooltip: 'Take Photo',
  class: 'my-custom-icon'
});
```

Resulting button:

```html
<button class="btn btn-default tool-bar-btn my-custom-icon" data-original-title="" title=""></button>
```

Then you can use stylesheet such as

```css
.my-custom-icon {
  background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJmZWF0aGVyIGZlYXRoZXItYXBlcnR1cmUiPjxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjEwIj48L2NpcmNsZT48bGluZSB4MT0iMTQuMzEiIHkxPSI4IiB4Mj0iMjAuMDUiIHkyPSIxNy45NCI+PC9saW5lPjxsaW5lIHgxPSI5LjY5IiB5MT0iOCIgeDI9IjIxLjE3IiB5Mj0iOCI+PC9saW5lPjxsaW5lIHgxPSI3LjM4IiB5MT0iMTIiIHgyPSIxMy4xMiIgeTI9IjIuMDYiPjwvbGluZT48bGluZSB4MT0iOS42OSIgeTE9IjE2IiB4Mj0iMy45NSIgeTI9IjYuMDYiPjwvbGluZT48bGluZSB4MT0iMTQuMzEiIHkxPSIxNiIgeDI9IjIuODMiIHkyPSIxNiI+PC9saW5lPjxsaW5lIHgxPSIxNi42MiIgeTE9IjEyIiB4Mj0iMTAuODgiIHkyPSIyMS45NCI+PC9saW5lPjwvc3ZnPg==);
  background-repeat: no-repeat;
  background-position: center;
}
```

Apart from being a more general solution to the problem, it also stays true to the Model-View-Controller model that HTML+CSS+JavaScript is almost always used for.
