### ISSUE TITLE
Looks out-of-place with Isotope UI.

### ISSUE THREAD

**Issue by k2b6s9j** [suda/tool-bar#75]
I've been told a picture's worth a thousand words, what does that make a screenshot?
![screen shot 2015-06-20 at 11 44 58 pm](https://cloud.githubusercontent.com/assets/594124/8270630/6a8aeff8-17a6-11e5-835e-5b49975e24a2.png)

**Comment by k2b6s9j** [comment]
I was able to achieve something I was fairly happy with by adding these lines of LESS to my `styles.less` file:

```less
.tool-bar {
  border: none;
  background: fadeout(@base-background-color, 100%);
  button.tool-bar-btn {
    background: inherit;
    border-color: fadeout(@base-background-color, 100%);
    &:focus, &:hover {
      border-color: fadeout(@base-background-color, 100%);
      background: lighten(fadeout(@base-background-color, 80%), 25%);
    }
  }
}
```

Here's how it looks with the background gradient:
![screen shot 2015-06-21 at 12 32 14 am](https://cloud.githubusercontent.com/assets/594124/8270737/4e7dea84-17ad-11e5-899e-2f484cab3eca.png)

And here's one without:
![screen shot 2015-06-21 at 12 32 32 am](https://cloud.githubusercontent.com/assets/594124/8270738/5506c7d6-17ad-11e5-9306-856e7c57d17a.png)
